# Site settings
name: Charles Neblett
email: charles.neblett@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Javascript, Node, React, Express, Startups, Agile, Pair Programming"
skills: "Cloud Engineer in Austin, TX"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/cneblett/
  - title: github
    url: https://www.github.com/cnebs
  # - title: twitter
  #   url: https://twitter.com/cnebs
  # - title: medium
  #   url: https://medium.com/@cgroom
  # - title: twitter
  #   url: https://twitter.com/chuck_groom
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2a76b4
  primary-rgb: "42, 118, 180"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
